// Dados de demonstração do painel do owner. Portados de
// ui_kits/painel-owner/ad-data.jsx do handoff.
//
// USADOS só quando `NEXT_PUBLIC_PAINEL_DEMO === '1'` OU como fallback das
// telas cuja rota ainda não existe (leva 2: Ritmo/Entregas/Histórico e os
// blocos de exemplo de Custos). Toda tela que mostra este dado exibe o selo
// "dado de exemplo" — some sozinho quando a rota real responde.
//
// Vocabulário de owner: nada de jargão na superfície. O termo de máquina só
// aparece atrás de "Ver detalhes técnicos" (o campo `tec` de cada item).

export const DEMO = {
  conta: 'Acme Engenharia',
  plano: 'Cloud Pro',
  usuario: 'Guilherme',

  semana: {
    rotulo: '21 a 27 de agosto',
    entregue: 7,
    meta: 10,
    porDia: [2, 1, 0, 2, 2, 0, 0],
    hojeIndex: 3,
    verdito: 'no ritmo',
    verditoNota: 'faltam 3 entregas e 3 dias úteis. O ritmo médio da semana dá conta.',
  },

  pulso: {
    ultimo: 'há 2 minutos',
    o_que: 'Jules subiu uma alteração no aviso de pagamento',
    quente: true,
  },

  kpis: [
    { l: 'Entregue esta semana', v: 7, n: 'de 10 na meta', tone: 'g' },
    { l: 'Esperando sua decisão', v: 2, n: 'a mais antiga há 18 min', tone: 'w', destaque: true },
    { l: 'Em andamento', v: 3, n: 'previsão: hoje', tone: '' },
    { l: 'Travado', v: 1, n: 'precisa de revisão manual', tone: 'b' },
  ],

  atuando: [
    {
      nome: 'Jules',
      papel: 'Desenvolvimento',
      o_que: 'Escrevendo o aviso de pagamento falhado',
      desde: 'há 26 min',
      estado: 'go',
      repo: 'Checkout',
      progresso: 68,
    },
    {
      nome: 'Revisão de qualidade',
      papel: 'Qualidade',
      o_que: 'Rodando os testes da última alteração',
      desde: 'há 4 min',
      estado: 'go',
      repo: 'Checkout',
      progresso: 40,
    },
    {
      nome: 'Análise de requisitos',
      papel: 'Planejamento',
      o_que: 'Parada, esperando sua decisão sobre dividir o pedido',
      desde: 'há 4 min',
      estado: 'wait',
      repo: 'Checkout',
      progresso: null,
    },
    {
      nome: 'Claude Code',
      papel: 'Desenvolvimento',
      o_que: 'Sem tarefa no momento',
      desde: '—',
      estado: 'idle',
      repo: '—',
      progresso: null,
    },
  ],

  pedidos: [
    {
      id: 412,
      t: 'Avisar cliente quando o pagamento falhar duas vezes',
      repo: 'Checkout',
      pri: 'P1',
      sit: 'Em desenvolvimento',
      d: 'go',
      resp: 'Jules',
      prev: 'Hoje, 17h',
      quando: 'há 12 min',
      tec: 'Issue #412 · 3 sub-issues · branch feat/dunning-notice · PR #131 aberto',
    },
    {
      id: 411,
      t: 'Exportar relatório de assinaturas em CSV',
      repo: 'Checkout',
      pri: 'P2',
      sit: 'Esperando você',
      d: 'wait',
      resp: '—',
      prev: '—',
      quando: 'há 2 h',
      tec: 'Issue #411 · aguardando resposta de dúvida RA-7',
    },
    {
      id: 409,
      t: 'Alerta de assinatura expirando',
      repo: 'Checkout',
      pri: 'P1',
      sit: 'Travado',
      d: 'block',
      resp: 'Qualidade',
      prev: 'Revisão manual',
      quando: 'há 4 dias',
      tec: 'Issue #409 · PR #124 · 3 testes falhando em billing/expiry.spec.ts',
    },
    {
      id: 408,
      t: 'Repetir a cobrança automaticamente quando o banco recusar',
      repo: 'Checkout',
      pri: 'P0',
      sit: 'Em produção',
      d: 'done',
      resp: 'Jules',
      prev: 'Entregue ontem',
      quando: 'ontem',
      tec: 'Issue #408 · PR #128 merged · 14 arquivos · 128 testes verdes',
    },
    {
      id: 405,
      t: 'Página de status pública',
      repo: 'Site',
      pri: 'P2',
      sit: 'Em produção',
      d: 'done',
      resp: 'Claude Code',
      prev: 'Entregue seg.',
      quando: 'há 3 dias',
      tec: 'Issue #405 · PR #119 merged · 6 arquivos',
    },
    {
      id: 402,
      t: 'Login por link mágico no app',
      repo: 'App',
      pri: 'P1',
      sit: 'Em produção',
      d: 'done',
      resp: 'Jules',
      prev: 'Entregue sex.',
      quando: 'há 6 dias',
      tec: 'Issue #402 · PR #112 merged · 21 arquivos',
    },
  ],

  decisoes: [
    {
      id: 'd1',
      papel: 'Planejamento',
      agente: 'Análise de requisitos',
      q: 'Posso quebrar "avisar cliente quando o pagamento falhar" em três partes menores?',
      ctx: 'O pedido cobre o aviso, a política de tentativas e o acompanhamento. Separado, cada parte entra em produção sozinha e mais rápido. Junto, sai tudo de uma vez, mas mais tarde.',
      op: ['Sim, três partes', 'Uma entrega só', 'Só o aviso agora'],
      st: 'pendente',
      quando: 'há 4 min',
      pedido: 412,
      tec: 'RA propõe sub-issues #412.1 (webhook), #412.2 (retry policy), #412.3 (telemetria) a partir de #412.',
    },
    {
      id: 'd2',
      papel: 'Desenvolvimento',
      agente: 'Jules',
      q: 'Qual serviço de e-mail devo usar para o aviso?',
      ctx: 'Nenhum está configurado no projeto. O Resend já é usado no seu site e sai mais barato neste volume; o SES exige configurar o domínio antes.',
      op: ['Resend', 'SES', 'Decido depois'],
      st: 'pendente',
      quando: 'há 18 min',
      pedido: 412,
      tec: 'Nenhum provider em env. resend@4.x já presente em acme/site package.json.',
    },
    {
      id: 'd3',
      papel: 'Planejamento',
      agente: 'Scrum Master',
      q: 'Subo a atualização de biblioteca junto com esta entrega?',
      ctx: 'Uma atualização de dependência está pendente. Junto economiza um ciclo de verificação; separado deixa cada mudança rastreável sozinha.',
      op: ['Junto', 'Separado'],
      st: 'respondida',
      resposta: 'Separado',
      quando: 'há 2 h',
      pedido: 408,
      tec: 'Dependabot PR #129 (prisma 5.18 para 5.22).',
    },
    {
      id: 'd4',
      papel: 'Produto',
      agente: 'Product Owner',
      q: 'O relatório em CSV pode esperar a próxima semana?',
      ctx: 'A fila de hoje já tem três itens mais urgentes.',
      op: ['Pode esperar', 'Não, hoje'],
      st: 'respondida',
      resposta: 'Pode esperar',
      quando: 'ontem',
      pedido: 411,
      tec: 'Issue #411 reprioritizada P2 para P3 no Projects V2.',
    },
  ],

  entregas: [
    {
      semana: 'Esta semana · 21 a 27 ago',
      total: 7,
      itens: [
        {
          t: 'Repetir a cobrança automaticamente quando o banco recusar',
          repo: 'Checkout',
          quando: 'ontem, 18h40',
          ganho: 'Recupera pagamentos que antes eram perdidos na primeira recusa.',
          resp: 'Jules',
          tec: 'PR #128 · 14 arquivos · 128 testes · ambiente isolado destruído após o merge',
        },
        {
          t: 'Página de status pública',
          repo: 'Site',
          quando: 'seg., 11h05',
          ganho: 'Clientes veem se há incidente sem abrir ticket.',
          resp: 'Claude Code',
          tec: 'PR #119 · 6 arquivos · deploy automático',
        },
        {
          t: 'Login por link mágico no app',
          repo: 'App',
          quando: 'sex., 16h20',
          ganho: 'Menos senha esquecida, menos suporte.',
          resp: 'Jules',
          tec: 'PR #112 · 21 arquivos · 64 testes',
        },
      ],
    },
    {
      semana: 'Semana passada · 14 a 20 ago',
      total: 9,
      itens: [
        {
          t: 'Cupom de desconto no checkout',
          repo: 'Checkout',
          quando: '19 ago',
          ganho: 'Time de vendas passou a rodar campanha sem pedir dev.',
          resp: 'Jules',
          tec: 'PR #101 · 18 arquivos',
        },
        {
          t: 'Exportar notas fiscais por período',
          repo: 'Checkout',
          quando: '16 ago',
          ganho: 'Fecha o mês sem planilha manual.',
          resp: 'Antigravity',
          tec: 'PR #96 · 9 arquivos',
        },
      ],
    },
  ],

  motores: [
    {
      nome: 'Jules',
      tipo: 'Desenvolvimento',
      usado: 14,
      limite: 20,
      unidade: 'tarefas nas últimas 24 h',
      nota: 'motor principal do Checkout',
    },
    {
      nome: 'Antigravity',
      tipo: 'Desenvolvimento',
      usado: 38,
      limite: 40,
      unidade: 'tarefas nas últimas 24 h',
      nota: 'quase no limite diário',
    },
    {
      nome: 'Claude Code',
      tipo: 'Desenvolvimento',
      usado: 3,
      limite: 40,
      unidade: 'tarefas nas últimas 24 h',
      nota: 'folga confortável',
    },
    {
      nome: 'Codex',
      tipo: 'Reserva',
      usado: 0,
      limite: 25,
      unidade: 'tarefas nas últimas 24 h',
      nota: 'entra só se os outros esgotarem',
    },
  ],

  custoPorRepo: [
    { repo: 'Checkout', tarefas: 41, pct: 68, entregas: 12 },
    { repo: 'Site', tarefas: 12, pct: 20, entregas: 3 },
    { repo: 'App', tarefas: 7, pct: 12, entregas: 1 },
  ],

  repos: [
    {
      nome: 'Checkout',
      full: 'acme/checkout-api',
      estado: 'go',
      estadoTxt: 'Produzindo',
      ultima: 'ontem, 18h40',
      fila: 3,
      agentes: ['Jules', 'Qualidade', 'Requisitos'],
      saude: 72,
      nota: 'Sem dono de revisão definido',
    },
    {
      nome: 'Site',
      full: 'acme/site',
      estado: 'go',
      estadoTxt: 'Produzindo',
      ultima: 'seg., 11h05',
      fila: 1,
      agentes: ['Claude Code'],
      saude: 88,
      nota: 'Tudo em ordem',
    },
    {
      nome: 'App',
      full: 'acme/mobile',
      estado: 'idle',
      estadoTxt: 'Sem fila',
      ultima: 'sex., 16h20',
      fila: 0,
      agentes: [],
      saude: 64,
      nota: 'Sem ambiente de homologação declarado',
    },
  ],

  regras: [
    {
      t: 'Nada vai para produção sem os testes passarem',
      d: 'A revisão de qualidade é obrigatória em toda entrega.',
      on: true,
      trava: true,
    },
    {
      t: 'Nenhum agente escreve direto no código principal',
      d: 'Todo trabalho acontece numa cópia isolada e volta como proposta.',
      on: true,
      trava: true,
    },
    {
      t: 'Dúvida trava a tarefa em vez de o agente decidir sozinho',
      d: 'É o que faz as decisões chegarem até você.',
      on: true,
      trava: false,
    },
    {
      t: 'Teto de tarefas por motor',
      d: 'Respeita a cota da sua própria assinatura de cada ferramenta.',
      on: true,
      trava: false,
    },
    {
      t: 'Aviso no Telegram a cada entrega',
      d: 'Além do painel, você recebe no celular.',
      on: true,
      trava: false,
    },
    {
      t: 'Pedido acima de P1 pode furar a fila',
      d: 'Desligado: hoje a fila respeita a ordem de prioridade sem exceção.',
      on: false,
      trava: false,
    },
  ],

  auditoria: [
    {
      quando: '27/08 14:02',
      quem: 'Revisão de qualidade',
      o_que: 'Aprovou a entrega do aviso de pagamento',
      ev: '128 testes passaram em 41s',
      tec: 'qa.gate · PR #131 · suite verde · ambiente isolado a41f',
    },
    {
      quando: '27/08 13:58',
      quem: 'Jules',
      o_que: 'Propôs alteração no aviso de pagamento',
      ev: '14 arquivos alterados',
      tec: 'dev.patch · branch feat/dunning-notice · PR #131',
    },
    {
      quando: '27/08 13:41',
      quem: 'Sistema',
      o_que: 'Não conseguiu acessar um repositório',
      ev: 'App do GitHub não instalado na organização',
      tec: 'clone.repo · REPO_ACCESS_DENIED · acme/mobile',
    },
    {
      quando: '27/08 13:30',
      quem: 'Análise de requisitos',
      o_que: 'Dividiu o pedido #412 em três partes',
      ev: '3 sub-itens criados',
      tec: 'ra.breakdown · #412.1 #412.2 #412.3',
    },
    {
      quando: '27/08 12:55',
      quem: 'Sistema',
      o_que: 'Releu o código do Checkout',
      ev: '1.284 símbolos, 312 arquivos',
      tec: 'cgc.index · kuzu graph rebuild',
    },
    {
      quando: '27/08 11:20',
      quem: 'Você',
      o_que: 'Respondeu "Separado" para o Scrum Master',
      ev: 'Decisão registrada no pedido #408',
      tec: 'decision.answer · d3 · via painel',
    },
    {
      quando: '26/08 18:40',
      quem: 'Jules',
      o_que: 'Entregou a repetição de cobrança',
      ev: 'Em produção',
      tec: 'dev.merge · PR #128 merged by gate',
    },
  ],
} as const

export const DIAS = ['seg', 'ter', 'qua', 'qui', 'sex', 'sáb', 'dom'] as const
